spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/practice?serverTimezone=Asia/Seoul
    username: test
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  cache:
    type: redis
    redis:
      time-to-live: 10000
      cache-null-values: true
  redis:
    host: localhost
    port: 6379
